
    create table Cancha (
        codigoCancha bigint generated by default as identity (start with 1),
        estaIluminada boolean not null,
        nombre varchar(255),
        color_idColor bigint,
        primary key (codigoCancha)
    )

    create table Color (
        idColor bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (idColor)
    )

    create table Constructor (
        codigoConstructor bigint generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (codigoConstructor)
    )

    create table Jugador (
        idJugador bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        nacimiento varbinary(255),
        nombre varchar(255),
        paleta_idPaleta bigint,
        primary key (idJugador)
    )

    create table Paleta (
        idPaleta bigint generated by default as identity (start with 1),
        grosor double not null,
        nombre varchar(255),
        color_idColor bigint,
        constructor_codigoConstructor bigint,
        primary key (idPaleta)
    )

    create table Participacion (
        idParticipacion bigint generated by default as identity (start with 1),
        jugador_idJugador bigint,
        paleta_idPaleta bigint,
        partido_idPartido bigint,
        primary key (idParticipacion)
    )

    create table Partido (
        idPartido bigint generated by default as identity (start with 1),
        finPartido varbinary(255),
        inicioPartido varbinary(255),
        cancha_codigoCancha bigint,
        reserva_idReserva bigint,
        primary key (idPartido)
    )

    create table Reserva (
        idReserva bigint generated by default as identity (start with 1),
        cancha_codigoCancha bigint,
        partido_idPartido bigint,
        responsable_idJugador bigint,
        primary key (idReserva)
    )

    alter table Cancha 
        add constraint FK_enm9h076jv1ubfxf2kg10tg0t 
        foreign key (color_idColor) 
        references Color

    alter table Jugador 
        add constraint FK_1ek067tb1r52fh7i4x7vj9gck 
        foreign key (paleta_idPaleta) 
        references Paleta

    alter table Paleta 
        add constraint FK_5tvmnx5h32994nwa8ii3e3nlu 
        foreign key (color_idColor) 
        references Color

    alter table Paleta 
        add constraint FK_n8y1bjom6mkch1gie5h3ohb8a 
        foreign key (constructor_codigoConstructor) 
        references Constructor

    alter table Participacion 
        add constraint FK_5nby10fawssr5kyhccuanw22x 
        foreign key (jugador_idJugador) 
        references Jugador

    alter table Participacion 
        add constraint FK_ci21ehickcodi9m08reywfl2d 
        foreign key (paleta_idPaleta) 
        references Paleta

    alter table Participacion 
        add constraint FK_q1hg0pv8lq5b0vs5tjdjcysua 
        foreign key (partido_idPartido) 
        references Partido

    alter table Partido 
        add constraint FK_qsfm2oen15kvd0dcwn6uljdmp 
        foreign key (cancha_codigoCancha) 
        references Cancha

    alter table Partido 
        add constraint FK_f8me8ox858q2cjxy69bdjw9v0 
        foreign key (reserva_idReserva) 
        references Reserva

    alter table Reserva 
        add constraint FK_65x4ix8362fllhuo6oyf79nav 
        foreign key (cancha_codigoCancha) 
        references Cancha

    alter table Reserva 
        add constraint FK_3mkc7dkty5xb3uxwvalnqshhx 
        foreign key (partido_idPartido) 
        references Partido

    alter table Reserva 
        add constraint FK_squ662gg9md3jo2jva0fjj7ab 
        foreign key (responsable_idJugador) 
        references Jugador
